name: Generate GitHub Animations

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Step 1: Generate Snake animation
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?palette=github-dark
            dist/snake-dark.svg?palette=github-dark&color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Step 2: Generate Pacman animation
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # Step 3: Move all generated files to dist (the actions above create them in the workspace root)
      - name: move generated files to dist
        run: |
          mkdir -p dist
          mv pacman-contribution-graph.svg dist/ || true
          mv pacman-contribution-graph-dark.svg dist/ || true

      # Step 4: Push snake and pacman SVGs to the output branch
      - name: push animations to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Generate GitHub Metrics (Stats, Languages, Achievements)
      - name: generate github-metrics.svg
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ANTI_METRIC_TOKEN }}
          filename: github-metrics.svg
          output_action: commit
          committer_branch: output
          config_timezone: Africa/Cairo
          debug: yes
          plugin_languages: yes
          plugin_languages_limit: 4
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0
